### ISSUE TITLE
POST/users/id/slots/add

### ISSUE THREAD

**Issue by on3iro** [on3iro/passCreator-Backend#14]
Adds a certain number of slots to the users maximum. (Usually when the user buys 'em)
The `packageName` part represents one of the available slot packages, e.g. small for 10 accounts, medium for 50 and large for 100...)

_JWT required!_

**Comment by PrettyPinkPonyOfDeath** [comment]
@on3iro:
I would rather suggest something like this:
`{
    'additionalSlots': '<number of additional slots>'
} 
`
Otherwise we would have to maintain the packageName in frontend and backend.

**Comment by on3iro** [comment]
@PrettyPinkPonyOfDeath Lets use package IDs instead. I don't wont the user to have granular control over the amount of slots he can buy. So it makes sense to offer slot packages. By referencing them by ID we avoid naming clashes.

**Comment by PrettyPinkPonyOfDeath** [comment]
@on3iro instead of IDs, let us use the number of slots to add, since we do not have much time left.
**request** will now look like `POST /users/<id>/slots/add/<number>`

**response:**
`
{
    'maxAccounts': 10
}
`
